### PR TITLE
Fix/warn value from package

### LINKED ISSUE #99: @emdaer/plugin-value-from-package should throw an error if the specified field does not exist.
- `emdaer` v3.0.0:
- `@emdaer/plugin-value-from-package` version v3.0.0:
- `node` 10.1.0:
- `npm` (or `yarn`) version: merp

Contents of your *.emdaer.md file:

```md
# <!--emdaer-p
  - '@emdaer/plugin-value-from-package'
  - value: name
-->

<!--emdaer-p
  - '@emdaer/plugin-shields'
  - shields:
      - alt: 'CircleCI'
        image: 'circleci/project/github/EditVR/editvr-frontend.svg'
        link: 'https://circleci.com/gh/EditVR/editvr-frontend'
        style: 'flat-square'
      - alt: 'Documented with emdaer'
        image: 'badge/📓-documented%20with%20emdaer-F06632.svg'
        link: 'https://github.com/emdaer/emdaer'
        style: 'flat-square'
      - alt: 'Commitizen friendly'
        image: 'badge/commitizen-friendly-brightgreen.svg'
        link: 'http://commitizen.github.io/cz-cli/'
        style: 'flat-square'
-->

<!--emdaer-p
  - '@emdaer/plugin-value-from-package'
  - value: description
-->

<!--emdaer-p
  - '@emdaer/plugin-contributors-details-github'
-->

<!--emdaer-t
  - '@emdaer/transform-prettier'
  - options:
      config: ./prettier.config.js
-->

```

Suggestion:
When `@emdaer/plugin-value-from-package` attempts to pull values from `package.json`, if the specified property does not exist within `package.json`, emdaer will silently print `undefined` for the value. Instead, perhaps it should throw an error?

### PR DESCRIPTION
**Pull request by infiniteluke**
**What**:
warn if value in package.json can't be found

**Why**:
`undefined` showing up in your readme silently is confusing

**How**:
check for typeof undefined 

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to AUTHORS 

closes #99

### CODE REVIEW

File: packages/plugin-value-from-package/src/index.js [hunk 1]
```diff
@@ -22,9 +22,14 @@ async function valueFromPackage({
   value: string,
   path: ?string,
 }): Promise<string> {
-  return JSON.parse(await fs.readFile(`${path || ''}package.json`, 'utf8'))[
+  const packagePath = `${path || ''}package.json`;
+  const packageValue = JSON.parse(await fs.readFile(packagePath, 'utf8'))[
     value
   ];
+  if (typeof packageValue === 'undefined') {
```
Comment (flipactual) [inline packages/plugin-value-from-package/src/index.js:29]: This makes me very uncomfortable, but undefined is not valid JSON (let's hope that spec holds), so alright

**Review by flipactual — APPROVED** [review]
